name: Build WDA with Frameworks

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-13
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Select Xcode 14
      run: sudo xcode-select -s /Applications/Xcode_14.3.1.app
      
    - name: Bootstrap WDA
      run: ./Scripts/bootstrap.sh -d
      
    - name: Build WDA with embedded frameworks
      run: |
        xcodebuild build-for-testing \
          -project WebDriverAgent.xcodeproj \
          -scheme WebDriverAgentRunner \
          -destination 'generic/platform=iOS' \
          -derivedDataPath build \
          ARCHS=arm64 \
          ONLY_ACTIVE_ARCH=NO \
          ENABLE_BITCODE=NO
    
    - name: Verify Frameworks exist
      run: |
        ls -lah build/Build/Products/Debug-iphoneos/WebDriverAgentRunner-Runner.app/Frameworks/ || echo "Frameworks folder missing!"
        
    - name: Create IPA with frameworks
      run: |
        cd build/Build/Products/Debug-iphoneos/
        mkdir Payload
        cp -r WebDriverAgentRunner-Runner.app Payload/
        cd Payload/WebDriverAgentRunner-Runner.app
        if [ -d "Frameworks" ]; then
          echo "Frameworks folder exists, size:"
          du -sh Frameworks/
        else
          echo "ERROR: No Frameworks folder!"
          exit 1
        fi
        cd ../..
        zip -r WebDriverAgent-WithFrameworks.ipa Payload/
        
    - name: Upload IPA
      uses: actions/upload-artifact@v3
      with:
        name: WebDriverAgent-iOS16-Complete
        path: build/Build/Products/Debug-iphoneos/WebDriverAgent-WithFrameworks.ipa
